const TeamData = [
  {
    id: 1,
    name: 'George Maina',
    title: 'CEO & Co-Founder',
    image: 'https://res.cloudinary.com/dwoxop5y0/image/upload/v1758952685/ceo_uxkrs8.jpg',
    linkedin: 'https://www.linkedin.com/in/george-maina-80a06366/',
    email: 'gmaina@shambarecords.com',
  },
  {
    id: 2,
    name: 'Kevin Kihara',
    title: 'Software Engineer',
    image: 'https://res.cloudinary.com/dwoxop5y0/image/upload/v1758951807/senior_xnihmp.png',
    linkedin: 'https://www.linkedin.com/in/kevin-kihara/',
    email: 'kevin.kihara@shambarecords.com',
  },
  {
    id: 3,
    name: 'Priscilla Wakahia',
    title: 'Software Engineer',
    image: 'https://res.cloudinary.com/dwoxop5y0/image/upload/v1758951807/dev1_hlqrpo.png',
    linkedin: 'https://www.linkedin.com/in/priscilla-wakahia/',
    email: 'priscilla.wakahia@shambarecords.com',
  },
  {
    id: 4,
    name: 'Samuel Cromwell',
    title: 'Software Engineer',
    image: 'https://res.cloudinary.com/dwoxop5y0/image/upload/v1758951808/dev2_txoydr.png',
    linkedin: 'https://www.linkedin.com/in/samuel-cromwell/',
    email: 'samuel.cromwell@shambarecords.com',
  },
  {
    id: 5,
    name: 'Ivy Muthoni',
    title: 'Software Engineer',
    image: 'https://res.cloudinary.com/dwoxop5y0/image/upload/v1758951807/dev3_x2vuk0.png',
    linkedin: 'https://www.linkedin.com/in/ivy-muthoni-7322b91b6/',
    email: 'ivy.muthoni@shambarecords.com',
  },
  {
    id: 6,
    name: 'Ronald Mcgarret',
    title: 'Software Engineer',
    image: 'https://res.cloudinary.com/dwoxop5y0/image/upload/v1758951807/dev4_w2efei.png',
    linkedin: 'https://www.linkedin.com/in/ronald-mcgarret/',
    email: 'ronald.mcgarret@shambarecords.com',
  },
  {
    id: 7,
    name: 'Mercy Nyawira',
    title: 'Secretary',
    image: 'https://res.cloudinary.com/dwoxop5y0/image/upload/v1758951807/sec_irdtio.png',
    linkedin: 'https://www.linkedin.com/company/shamba-records/posts/?feedView=all',
    email: 'info@shambarecords.com',
  },
];

export default TeamData;
